theme: jekyll-theme-minimal
title: Noah Royce
<img src="https://github.com/nroyce7/nroyce7.github.io/blob/master/head%20shot.jpg?raw=true" width="300">
description: Expanding my research skills through labwork and REUs in order to prepare myself for graduate level studies and an eventual career in physics research.
