theme: jekyll-theme-slate
title: Noah Royce
description: Expanding my research skills through labwork and REUs in order to prepare myself for graduate level studies and an eventual career in physics research.
