theme: jekyll-theme-minimal
title: Noah Royce
logo: head_shot.jpg
description: Expanding my research skills through labwork and REUs in order to prepare myself for graduate level studies and an eventual career in physics research. <br /> Twitch
