theme: jekyll-theme-midnight
title: Noah Royce
description: Expanding my research skills through labwork and REUs in order to prepare myself for graduate level studies and an eventual career in physics research.[Research Gate](https://www.researchgate.net/profile/Noah_Royce)
