theme: jekyll-theme-minimal
title: Noah Royce
logo: thumbnail.png
description: An aspiring Applied Mathematician with a deep passion for science and research, who can use creativity and quantitative reasoning to surmount any obstacle.
